
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.vm.hostname = "master"
  config.vm.network "private_network", ip: "172.16.0.1"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "master"
    vb.memory = 2048
    vb.cpus = 2
  end
end
