SERVICES = {
  'master' => {
    ip: '172.16.0.11',
    hostname: 'master',
    provider: {
      name: 'master',
      memory: 2048,
      cpus: 2
    }
  },
  'worker1' => {
    ip: '172.16.0.12',
    hostname: 'worker1',
    provider: {
      name: 'worker1',
      memory: 2048,
      cpus: 2
    }
  },
  'worker2' => {
    ip: '172.16.0.13',
    hostname: 'worker2',
    provider: {
      name: 'worker2',
      memory: 2048,
      cpus: 2
    }
  },
  'ansible' => {
    ip: '172.16.0.14',
    hostname: 'ansible',
    provider: {
      name: 'ansible',
      memory: 1024,
      cpus: 2
    }
  }
}

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  
  SERVICES.each do |name, options|
    config.vm.define name do |node|
      node.vm.hostname = options[:hostname] 
      node.vm.network "private_network", ip: options[:ip], netmask: "255.255.0.0"
      node.vm.provider "virtualbox" do |vb|
        vb.name = options[:provider][:name]
        vb.memory = options[:provider][:memory]
        vb.cpus = options[:provider][:cpus]
      end
      #node.vm.provision "shell", path: "setupk8s.sh"
    end
  end
end