#Создайте Dockerfile с многоэтапной сборкой для приложения на Go или Java.
#На первом этапе соберите приложение.
#На втором этапе скопируйте собранный бинарник в минимальный образ на основе alpine.
#Соберите образ и запустите контейнер, чтобы убедиться, что приложение работает.

FROM golang:1.23
WORKDIR /src
COPY <<EOF ./main.go
package main

import "fmt"

func main() {
  fmt.Println("hello, world")
}
EOF
RUN go build -o /bin/hello ./main.go

FROM alpine
COPY --from=0 /bin/hello /bin/hello
CMD ["/bin/hello"]
#docker build -t task_3 .
#docker run --rm task_3
