name: task_6

services:
  web:
    image: task_6
    networks:
      - app_network
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
