FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3 python3-pip git
RUN pip3 install flask
RUN git clone https://github.com/mmumshad/simple-webapp-flask.git /opt/simple-webapp-flask

WORKDIR /opt/simple-webapp-flask
ENV FLASK_APP=app.py
ENTRYPOINT ["flask", "run", "--host=0.0.0.0", "--port=8080"]
EXPOSE 8080

#docker build -t task_6 .
#docker run --name task_6 -p 3000:8080 task_6