name: task_2
services:
  ubuntu:
    image: task_2_ubuntu
    env_file:
      - .env
    container_name: ubuntu
    networks:
      - app_network
  postgres:
    image: postgres:14.16-alpine3.20
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge